//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaDBContainer : DbContext
    {
        public BibliotekaDBContainer()
            : base("name=FurnitureDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Osoba> Osobas { get; set; }
        public virtual DbSet<Clan> Clans { get; set; }
        public virtual DbSet<Clanarina> Clanarinas { get; set; }
        public virtual DbSet<Bibliotekar> Bibliotekars { get; set; }
        public virtual DbSet<Biblioteka> Bibliotekas { get; set; }
        public virtual DbSet<Knjiga> Knjigas { get; set; }
        public virtual DbSet<Izdanje> Izdanjes { get; set; }
        public virtual DbSet<Izdavac> Izdavacs { get; set; }
        public virtual DbSet<Primerak> Primeraks { get; set; }
        public virtual DbSet<Za_Iznajmljivanje> Za_Iznajmljivanje { get; set; }
        public virtual DbSet<Za_Prodaju> Za_Prodaju { get; set; }
    }
}
