//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliotekar
    {
        public short ID_Bibliotekara { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public short BibliotekaPIB { get; set; }
    
        public virtual Biblioteka Biblioteka { get; set; }
    }
}
