//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public int ID_clana { get; set; }
        public int OsobaJMBG { get; set; }
    
        public virtual Osoba Osoba { get; set; }
    }
}
