//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izdanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Izdanje()
        {
            this.Primeraks = new HashSet<Primerak>();
        }
    
        public short Rbr_Izdanja { get; set; }
        public short KnjigaID_Knjige { get; set; }
        public short IzdavacID_Izdavaca { get; set; }
    
        public virtual Knjiga Knjiga { get; set; }
        public virtual Izdavac Izdavac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Primerak> Primeraks { get; set; }
    }
}
