//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Knjiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Knjiga()
        {
            this.Bibliotekas = new HashSet<Biblioteka>();
            this.Izdanjes = new HashSet<Izdanje>();
        }
    
        public short ID_Knjige { get; set; }
        public string Autor { get; set; }
        public string Naziv { get; set; }
        public int Kolicina { get; set; }
        public string Zanr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biblioteka> Bibliotekas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Izdanje> Izdanjes { get; set; }
    }
}
