//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Primerak
    {
        public short ID_Primerka { get; set; }
        public short IzdanjeRbr_Izdanja { get; set; }
    
        public virtual Izdanje Izdanje { get; set; }
        public virtual Za_Iznajmljivanje Za_Iznajmljivanje { get; set; }
        public virtual Za_Prodaju Za_Prodaju { get; set; }
    }
}
