//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Za_Prodaju
    {
        public long Cena_Knjige { get; set; }
        public short PrimerakID_Primerka { get; set; }
    
        public virtual Primerak Primerak { get; set; }
    }
}
